export const MESSAGE_ERROR = {
    INVALID_DATA: "DADOS INVÁLIDOS",
    INTERNAL_ERROR: "ERRO INTERNO"
}

export const MESSAGE_SUCCESS = {
    INSERT_ITEM: "ITEM CRIADO COM SUCESSO NO BANCO DE DADOS",
    UPDATE_ITEM: "ITEM ATUALIZADO COM SUCESSO NO BANCO DE DADOS",
    DELETE_ITEM: "ITEM EXCLUÍDO COM SUCESSO NO BANCO DE DADOS",
    JWT_CREATED: "TOKEN JWT CRIADO COM SUCESSO",
}